# IPython log file

runfile('D:/Final Project/qqwqw/che/cnn.py', wdir='D:/Final Project/qqwqw/che')
get_ipython().run_line_magic('logstart', '-o')
get_ipython().run_line_magic('logstart', '-o')
get_ipython().run_line_magic('logstart', '-o')
get_ipython().run_line_magic('logstart', '-o')
runfile('D:/Final Project/qqwqw/che/verify.py', wdir='D:/Final Project/qqwqw/che')
get_ipython().run_line_magic('logstart', '-o')
get_ipython().run_line_magic('logstart', '-o')
get_ipython().run_line_magic('save', 'log_list.py _oh[i]')
get_ipython().run_line_magic('save', 'file_name.py _')
runfile('D:/Final Project/qqwqw/che/cnn.py', wdir='D:/Final Project/qqwqw/che')
get_ipython().run_line_magic('save', 'log.py _')
runfile('D:/Final Project/qqwqw/che/cnn.py', wdir='D:/Final Project/qqwqw/che')
runfile('D:/Final Project/qqwqw/che/cnn.py', wdir='D:/Final Project/qqwqw/che')
runfile('D:/Final Project/qqwqw/che/cnn.py', wdir='D:/Final Project/qqwqw/che')
runfile('D:/Final Project/qqwqw/che/cnn.py', wdir='D:/Final Project/qqwqw/che')
runfile('D:/Final Project/qqwqw/che/cnn.py', wdir='D:/Final Project/qqwqw/che')
runfile('D:/Final Project/qqwqw/che/cnn.py', wdir='D:/Final Project/qqwqw/che')
runfile('D:/Final Project/qqwqw/che/cnn.py', wdir='D:/Final Project/qqwqw/che')
runfile('D:/Final Project/qqwqw/che/verify.py', wdir='D:/Final Project/qqwqw/che')
runfile('D:/Final Project/qqwqw/che/verify.py', wdir='D:/Final Project/qqwqw/che')
runfile('D:/Final Project/qqwqw/che/cnn.py', wdir='D:/Final Project/qqwqw/che')
runfile('D:/Final Project/qqwqw/che/cnn.py', wdir='D:/Final Project/qqwqw/che')
runfile('D:/Final Project/qqwqw/che/verify.py', wdir='D:/Final Project/qqwqw/che')
runfile('D:/Final Project/qqwqw/che/verify.py', wdir='D:/Final Project/qqwqw/che')
runfile('D:/Final Project/qqwqw/che/verify.py', wdir='D:/Final Project/qqwqw/che')
runfile('D:/Final Project/qqwqw/che/verify.py', wdir='D:/Final Project/qqwqw/che')
runfile('D:/Final Project/qqwqw/che/verify.py', wdir='D:/Final Project/qqwqw/che')
